name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: Install dependencies
      run: |
        cd $HOME
        git clone https://github.com/google/googletest.git
        cd googletest
        git checkout e93da23920e5b6887d6a6a291c3a59f83f5b579e
        mkdir _build && cd _build
        cmake -DCMAKE_CXX_FLAGS="-std=c++11 -march=x86-64 -mtune=generic" ..
        make -j$(nproc)
        sudo make install
        cd $GITHUB_WORKSPACE
        echo $GITHUB_WORKSPACE
    - name: CMake
      run: |
          mkdir build && cd build
          cmake ..
    - name: Check format
      run: |
          cd build
          make format-check
    - name: Build
      run: |
          cd build
          make -j$(nproc)
    - name: Test
      run: |
          cd build
          ctest --output-on-failure
